name: Build Opposition Report PDF
on: [push, pull_request]
jobs:
  build_opposition_report_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: DP_opposition-report_eng_v2.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: DP_opposition-report_eng_v2.pdf
